class M5ImportanceAnalyzer:
    """
    M5.4 — Topic Importance / Priority Analyzer

    This service converts the factual examination statistics
    generated by M5.3 into a transparent importance score.

    IMPORTANT:

    This is NOT an LLM-based decision.

    We deliberately use deterministic rules so that CramWise
    can explain WHY a topic received a particular priority.

    Input:
        marks_frequency_analytics.json

    Output:
        importance_analytics.json
    """

    # ======================================================
    # SCORE WEIGHTS
    # ======================================================

    # Total score = 100

    QUESTION_FREQUENCY_WEIGHT = 30
    PAPER_RECURRENCE_WEIGHT = 25
    TOTAL_MARKS_WEIGHT = 25
    LONG_QUESTION_WEIGHT = 20

    # ======================================================
    # INITIALIZATION
    # ======================================================

    def __init__(
        self,
        topic_analytics: list[dict],
    ):
        """
        Parameters
        ----------
        topic_analytics:
            Output generated by M5.3.
        """

        self.topic_analytics = topic_analytics

    # ======================================================
    # MAIN ANALYSIS
    # ======================================================

    def analyze(self) -> list[dict]:
        """
        Calculate an importance score for every topic.

        Returns
        -------
        list[dict]
            Topic importance records.
        """

        if not self.topic_analytics:
            return []

        # --------------------------------------------------
        # Find maximum values in the dataset.
        #
        # We use dataset-relative normalization instead
        # of hard-coded assumptions.
        # --------------------------------------------------

        max_questions = max(
            topic["question_count"]
            for topic in self.topic_analytics
        )

        max_papers = max(
            topic["paper_count"]
            for topic in self.topic_analytics
        )

        max_total_marks = max(
            topic["total_marks"]
            for topic in self.topic_analytics
        )

        max_long_questions = max(
            topic["ten_mark_questions"]
            for topic in self.topic_analytics
        )

        # Prevent division by zero.
        max_questions = max(
            max_questions,
            1
        )

        max_papers = max(
            max_papers,
            1
        )

        max_total_marks = max(
            max_total_marks,
            1
        )

        max_long_questions = max(
            max_long_questions,
            1
        )

        results = []

        # --------------------------------------------------
        # ANALYZE EACH TOPIC
        # --------------------------------------------------

        for topic in self.topic_analytics:

            # ----------------------------------------------
            # 1. QUESTION FREQUENCY SCORE
            # ----------------------------------------------

            question_frequency_score = (
                topic["question_count"]
                / max_questions
            ) * self.QUESTION_FREQUENCY_WEIGHT

            # ----------------------------------------------
            # 2. PAPER RECURRENCE SCORE
            # ----------------------------------------------

            paper_recurrence_score = (
                topic["paper_count"]
                / max_papers
            ) * self.PAPER_RECURRENCE_WEIGHT

            # ----------------------------------------------
            # 3. TOTAL MARKS SCORE
            # ----------------------------------------------

            total_marks_score = (
                topic["total_marks"]
                / max_total_marks
            ) * self.TOTAL_MARKS_WEIGHT

            # ----------------------------------------------
            # 4. LONG QUESTION SCORE
            # ----------------------------------------------

            long_question_score = (
                topic["ten_mark_questions"]
                / max_long_questions
            ) * self.LONG_QUESTION_WEIGHT

            # ----------------------------------------------
            # FINAL SCORE
            # ----------------------------------------------

            importance_score = (
                question_frequency_score
                + paper_recurrence_score
                + total_marks_score
                + long_question_score
            )

            # Keep the score between 0 and 100.
            importance_score = min(
                max(
                    importance_score,
                    0.0
                ),
                100.0
            )

            # ----------------------------------------------
            # PRIORITY LABEL
            # ----------------------------------------------

            priority = (
                self._get_priority(
                    importance_score
                )
            )

            # ----------------------------------------------
            # BUILD RESULT
            # ----------------------------------------------

            result = {
                # Topic identity.
                "topic_id": topic["topic_id"],
                "topic": topic["topic"],
                "subtopic": topic["subtopic"],
                "unit": topic["unit"],

                # Raw examination statistics.
                "question_count": topic[
                    "question_count"
                ],
                "paper_count": topic[
                    "paper_count"
                ],
                "total_marks": topic[
                    "total_marks"
                ],
                "average_marks": topic[
                    "average_marks"
                ],

                # Score components.
                "question_frequency_score": round(
                    question_frequency_score,
                    2
                ),

                "paper_recurrence_score": round(
                    paper_recurrence_score,
                    2
                ),

                "total_marks_score": round(
                    total_marks_score,
                    2
                ),

                "long_question_score": round(
                    long_question_score,
                    2
                ),

                # Final importance.
                "importance_score": round(
                    importance_score,
                    2
                ),

                "priority": priority,

                # Keep useful examination signals.
                "ten_mark_questions": topic[
                    "ten_mark_questions"
                ],

                "five_mark_questions": topic[
                    "five_mark_questions"
                ],

                "short_questions": topic[
                    "short_questions"
                ],

                "marks_distribution": topic[
                    "marks_distribution"
                ],

                # Keep dependency information.
                "independent_count": topic[
                    "independent_count"
                ],

                "dependent_count": topic[
                    "dependent_count"
                ],

                "prerequisites": topic[
                    "prerequisites"
                ],

                # Keep the actual PYQs.
                "questions": topic[
                    "questions"
                ],

                "papers": topic[
                    "papers"
                ],
            }

            results.append(
                result
            )

        # --------------------------------------------------
        # SORT BY IMPORTANCE
        # --------------------------------------------------

        results.sort(
            key=lambda item: (
                -item["importance_score"],
                item["topic_id"]
            )
        )

        return results

    # ======================================================
    # PRIORITY CLASSIFICATION
    # ======================================================

    @staticmethod
    def _get_priority(
        score: float,
    ) -> str:
        """
        Convert numerical importance score into a
        human-readable priority.

        80–100 : VERY HIGH
        60–79  : HIGH
        40–59  : MEDIUM
        0–39   : LOW
        """

        if score >= 75:
            return "VERY HIGH"

        if score >= 55:
            return "HIGH"

        if score >= 35:
            return "MEDIUM"

        return "LOW"