from collections import Counter


class M5MarksFrequencyAnalyzer:
    """
    M5.3 — Marks & Frequency Analyzer

    Takes the topic-level output generated by M5.2 and
    calculates factual examination statistics for every topic.

    IMPORTANT:
    This class does NOT calculate the final importance score.

    It only answers:

        How often was this topic asked?
        How many marks were associated with it?
        What marks were used?
        In how many papers did it appear?
        How many long/short questions were asked?

    The final importance/priority calculation will happen
    in a later M5 milestone.
    """

    def __init__(
        self,
        topic_analytics: list[dict],
    ):
        """
        Parameters
        ----------
        topic_analytics:
            Output produced by M5.2 Topic Aggregator.
        """

        self.topic_analytics = topic_analytics

    # ======================================================
    # ANALYZE ALL TOPICS
    # ======================================================

    def analyze(self) -> list[dict]:
        """
        Calculate marks and frequency statistics for every
        syllabus topic.

        Returns
        -------
        list[dict]
            One analytics record per topic.
        """

        analyzed_topics = []

        for topic in self.topic_analytics:

            # --------------------------------------------------
            # COPY BASIC TOPIC INFORMATION
            # --------------------------------------------------

            result = {
                "topic_id": topic["topic_id"],
                "topic": topic["topic"],
                "subtopic": topic["subtopic"],
                "unit": topic["unit"],

                # Existing M5.2 statistics.
                "question_count": topic["question_count"],
                "paper_count": topic["paper_count"],
                "papers": topic["papers"],

                # Existing marks information.
                "total_marks": topic["total_marks"],
                "average_marks": topic["average_marks"],

                # Question-level marks analysis.
                "marks_distribution": {},
                "max_marks": 0.0,

                # Useful exam-pattern signals.
                "ten_mark_questions": 0,
                "five_mark_questions": 0,
                "short_questions": 0,

                # Dependency information is carried forward
                # because later analytics may use it.
                "independent_count": topic[
                    "independent_count"
                ],
                "dependent_count": topic[
                    "dependent_count"
                ],
                "prerequisites": topic[
                    "prerequisites"
                ],

                # Preserve the actual PYQs.
                "questions": topic["questions"],
            }

            # --------------------------------------------------
            # EXTRACT MARKS
            # --------------------------------------------------

            marks = []

            for question in topic["questions"]:

                question_marks = question.get(
                    "marks"
                )

                if question_marks is None:
                    continue

                try:
                    marks.append(
                        float(question_marks)
                    )

                except (
                    TypeError,
                    ValueError,
                ):
                    continue

            # --------------------------------------------------
            # MARKS DISTRIBUTION
            # --------------------------------------------------

            counter = Counter(
                marks
            )

            result["marks_distribution"] = {
                self._format_marks(mark): count
                for mark, count in sorted(
                    counter.items()
                )
            }

            # --------------------------------------------------
            # MAXIMUM MARKS
            # --------------------------------------------------

            if marks:
                result["max_marks"] = max(
                    marks
                )

            # --------------------------------------------------
            # QUESTION TYPE COUNTS
            # --------------------------------------------------

            for mark in marks:

                # 10-mark questions.
                if mark == 10:
                    result[
                        "ten_mark_questions"
                    ] += 1

                # 5-mark questions.
                elif mark == 5:
                    result[
                        "five_mark_questions"
                    ] += 1

                # Anything below 5 is treated as
                # a short-answer question.
                elif mark < 5:
                    result[
                        "short_questions"
                    ] += 1

            analyzed_topics.append(
                result
            )

        # ------------------------------------------------------
        # DETERMINISTIC ORDER
        # ------------------------------------------------------

        analyzed_topics.sort(
            key=lambda item: item["topic_id"]
        )

        return analyzed_topics

    # ======================================================
    # MARK FORMATTER
    # ======================================================

    @staticmethod
    def _format_marks(
        marks: float,
    ) -> str:
        """
        Convert marks to clean JSON keys.

        Examples:

            10.0 -> "10"
            5.0  -> "5"
            2.5  -> "2.5"
        """

        if marks.is_integer():
            return str(
                int(marks)
            )

        return str(
            marks
        )