import json
from pathlib import Path

from app.schemas.recommendation import (
    RecommendationRequest
)

from app.services.llm_analysis.syllabus_catalog_service import (
    SyllabusCatalogService
)


class M6TopicSelector:
    """
    M6.2 — Subject Resolver + Topic Selector.

    Responsibilities:

        1. Resolve student's subject name to course code
        2. Load M5 priority analytics
        3. Select topics belonging to that subject
        4. Remove topics already completed by the student
        5. Return candidate topics

    Example:

        Student:
            Compiler Design

        M2:
            Compiler Design -> BCS 306

        M5:
            BCS306 topics

        Output:
            remaining Compiler Design topics

    This class does NOT:

        - calculate importance
        - calculate study time
        - create final study order
        - call Groq
        - perform RAG
    """

    def __init__(
        self,
        catalog: SyllabusCatalogService,
        priority_path: Path,
    ):
        """
        Parameters
        ----------
        catalog:
            Existing M2 syllabus catalog.

        priority_path:
            Path to M5.6 priority_analytics.json.
        """

        self.catalog = catalog
        self.priority_path = Path(priority_path)

        self.priority_data = self._load_priority_data()

    # ======================================================
    # LOAD M5 PRIORITY DATA
    # ======================================================

    def _load_priority_data(self) -> list[dict]:
        """
        Load priority_analytics.json generated by M5.6.
        """

        if not self.priority_path.exists():

            raise FileNotFoundError(
                "Priority analytics file not found: "
                f"{self.priority_path}"
            )

        with open(
            self.priority_path,
            "r",
            encoding="utf-8",
        ) as file:

            data = json.load(file)

        if not isinstance(data, list):

            raise ValueError(
                "priority_analytics.json must contain a list."
            )

        return data

    # ======================================================
    # RESOLVE SUBJECT
    # ======================================================

    def resolve_subject(
        self,
        subject_name: str,
    ) -> str:
        """
        Resolve a human-readable subject name to its
        internal course code using M2.

        Example:

            Compiler Design
                    ↓
                 BCS 306

        Matching is case-insensitive.
        """

        normalized_name = (
            subject_name.strip().lower()
        )

        if not normalized_name:

            raise ValueError(
                "Subject name cannot be empty."
            )

        # --------------------------------------------------
        # GET ALL SYLLABUS RECORDS
        # --------------------------------------------------

        # M2 stores the syllabus records and exposes them
        # through its catalog.
        #
        # We inspect the catalog records here instead of
        # maintaining another subject mapping.

        records = getattr(
            self.catalog,
            "syllabus",
            None
        )

        if records is None:

            records = getattr(
                self.catalog,
                "records",
                None
            )

        if records is None:

            raise AttributeError(
                "SyllabusCatalogService does not expose "
                "syllabus records."
            )

        matched_codes = set()

        for record in records:

            course_name = str(
                record.get(
                    "course_name",
                    ""
                )
            ).strip().lower()

            if course_name == normalized_name:

                course_code = record.get(
                    "course_code"
                )

                if course_code:

                    matched_codes.add(
                        course_code
                    )

        # --------------------------------------------------
        # NO MATCH
        # --------------------------------------------------

        if not matched_codes:

            raise ValueError(
                f"Subject not found in syllabus catalog: "
                f"{subject_name}"
            )

        # --------------------------------------------------
        # AMBIGUOUS MATCH
        # --------------------------------------------------

        if len(matched_codes) > 1:

            raise ValueError(
                f"Multiple course codes found for "
                f"subject '{subject_name}': "
                f"{sorted(matched_codes)}"
            )

        return next(
            iter(matched_codes)
        )

    # ======================================================
    # GET SUBJECT TOPICS
    # ======================================================

    def get_subject_topics(
        self,
        course_code: str,
    ) -> list[dict]:
        """
        Get all M5 priority records belonging to
        the requested subject.

        Example:

            BCS 306
                ↓
            BCS306_U1_...
            BCS306_U2_...
            ...
        """

        normalized_code = (
            course_code
            .replace(" ", "")
            .upper()
        )

        topics = []

        for topic in self.priority_data:

            topic_id = str(
                topic.get(
                    "topic_id",
                    ""
                )
            ).replace(
                " ",
                ""
            ).upper()

            # Topic IDs begin with the course code.

            if topic_id.startswith(
                normalized_code
            ):

                topics.append(
                    topic
                )

        return topics

    # ======================================================
    # SELECT CANDIDATE TOPICS
    # ======================================================

    def select(
        self,
        request: RecommendationRequest,
    ) -> dict:
        """
        Resolve subject and return all eligible topics.

        Completed topics are removed.

        No ranking or time allocation is performed here.
        """

        # --------------------------------------------------
        # STEP 1 — RESOLVE SUBJECT
        # --------------------------------------------------

        course_code = self.resolve_subject(
            request.subject
        )

        # --------------------------------------------------
        # STEP 2 — GET SUBJECT TOPICS
        # --------------------------------------------------

        all_topics = self.get_subject_topics(
            course_code
        )

        if not all_topics:

            raise ValueError(
                f"No priority analytics found for "
                f"subject {request.subject} "
                f"({course_code})."
            )

        # --------------------------------------------------
        # STEP 3 — REMOVE COMPLETED TOPICS
        # --------------------------------------------------

        completed = set(
            request.completed_topics
        )

        remaining_topics = [
            topic
            for topic in all_topics
            if topic["topic_id"]
            not in completed
        ]

        # --------------------------------------------------
        # STEP 4 — RETURN STRUCTURED RESULT
        # --------------------------------------------------

        return {
            "subject": request.subject,
            "course_code": course_code,
            "total_topics": len(all_topics),
            "completed_topics": len(
                all_topics
            ) - len(
                remaining_topics
            ),
            "candidate_topics": remaining_topics,
        }