from pydantic import BaseModel, Field, field_validator


class RecommendationRequest(BaseModel):
    """
    Student-facing input for the CramWise recommendation engine.
    """

    subject: str = Field(
        description="Human-readable subject name."
    )

    available_hours: float = Field(
        gt=0,
        le=24,
        description="Number of hours available for studying."
    )

    exam_type: str | None = Field(
        default=None,
        description="Optional exam type: MIDTERM or ENDTERM."
    )

    completed_topics: list[str] = Field(
        default_factory=list,
        description="Topic IDs already completed by the student."
    )

    @field_validator("subject")
    @classmethod
    def validate_subject(cls, value: str) -> str:

        value = value.strip()

        if not value:
            raise ValueError(
                "subject cannot be empty."
            )

        value = " ".join(value.split())

        return value

    @field_validator("exam_type")
    @classmethod
    def validate_exam_type(
        cls,
        value: str | None,
    ) -> str | None:

        if value is None:
            return None

        value = value.strip().upper()

        if not value:
            return None

        if value not in {
            "MIDTERM",
            "ENDTERM",
        }:
            raise ValueError(
                "exam_type must be either MIDTERM or ENDTERM."
            )

        return value

    @field_validator("completed_topics")
    @classmethod
    def validate_completed_topics(
        cls,
        value: list[str],
    ) -> list[str]:

        cleaned = []

        for topic_id in value:

            topic_id = topic_id.strip()

            if not topic_id:
                continue

            if topic_id not in cleaned:
                cleaned.append(topic_id)

        return cleaned


# ==========================================================
# M6.3 LLM RECOMMENDATION
# ==========================================================


class RecommendedTopic(BaseModel):
    """
    One topic recommended by the LLM.
    """

    topic_id: str = Field(
        description=(
            "Must exactly match one of the supplied "
            "candidate topic IDs."
        )
    )

    study_order: int = Field(
        ge=1,
        description="Order in which the student should study the topic."
    )

    recommended_minutes: int = Field(
        gt=0,
        description="Recommended study time in minutes."
    )

    reason: str = Field(
        min_length=1,
        description="Short explanation for recommending this topic."
    )


class PersonalizedRecommendation(BaseModel):
    """
    Structured recommendation generated by M6.3.
    """

    recommendations: list[RecommendedTopic] = Field(
        default_factory=list
    )

    total_minutes: int = Field(
        ge=0
    )